#!/usr/bin/env python

import logging
import argparse
from apman.models import PackageLogEntry


def main():

    # Some parser set up
    parser = argparse.ArgumentParser(description='Set up database according to apman global config.')
    parser.add_argument('-vv', '--debug', help="Print lots of debugging statements", action="store_const", dest="loglevel", const=logging.DEBUG, default=logging.WARNING)
    args = parser.parse_args()

    # logging setup
    logging.basicConfig(
        format='%(asctime)s|%(levelname)s|%(message)s',
        datefmt='%m/%d/%Y %I:%M:%S',
        level=args.loglevel)

    # Spin round these 
    logging.info("Querying Log")
    PackageLogEntry.print_last_n(10)

if __name__ == '__main__':
    main()
